name: Python Workflow

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a branch
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version you need

      - name: Run Python script
        run: 
          python -m pip install requests
          proj_gidp_ba.py  # Replace 'your_script.py' with the name of your Python file
