name: Python Workflow

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Python script
        run: proj_gidp_ba.py  # Replace 'your_script.py' with the name of your Python file
