name: Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a branch
      - uses: actions/checkout@main

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use
      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies
      - name: Run script
        run: proj_gidp_ba.py  # Replace with the path to your Python script
