name: Python Workflow

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv  # Specify the name of your conda environment
          environment-file: environment.yml  # Path to environment file if you have one
          
      - name: Install dependencies
        run: conda install --file requirements.txt  # Install dependencies from requirements.txt
      
      - name: Run Python script
        run: python proj_gidp_ba.py  # Replace 'your_script.py' with the name of your Python script
